kind: Namespace
apiVersion: v1
metadata:
  name: headlamp
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 10m0s
  path: ./headlamp
  prune: true
  dependsOn:
    # requires gateway API to be installed
    - name: ingress
      namespace: ingress
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
