kind: Namespace
apiVersion: v1
metadata:
  name: operators
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: operators
  namespace: operators
spec:
  interval: 10m0s
  path: ./operators
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
