apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/headlamp/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 24h
  chart: headlamp
  sourceRef:
    kind: HelmRepository
    name: headlamp
  version: "0.37.x"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 12h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chartRef:
    kind: HelmChart
    name: headlamp
  values:
    config:
      oidc:
        secret:
          create: false
        externalSecret:
          name: oidc
          enabled: true
        usePKCE: false
      pluginsDir: /build/plugins
    ingress:
      enabled: false
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    volumes:
      - name: headlamp-plugins
        emptyDir: { }
    initContainers:
      - command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown -R 100:101 /build
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        imagePullPolicy: Always
        name: headlamp-plugin-flux
        securityContext:
          runAsNonRoot: false
          privileged: false
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
      - command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown -R 100:101 /build
        image: ghcr.io/headlamp-k8s/headlamp-plugin-cert-manager:latest
        imagePullPolicy: Always
        name: headlamp-plugin-cert-manager
        securityContext:
          runAsNonRoot: false
          privileged: false
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: headlamp
spec:
  hostnames:
  - headlamp.kbs610.click
  parentRefs:
    - name: cloudflare
      namespace: ingress
  rules:
    - backendRefs:
        - name: headlamp
          port: 80
