apiVersion: v1
kind: Secret
metadata:
  name: ca
  annotations:
    replicator.v1.mittwald.de/replicate-to: trainy
stringData:
  ca.crt: >
    -----BEGIN CERTIFICATE-----
    MIIDazCCAlOgAwIBAgIUBLW4aVrYrhiivhywAp6JgYlB6SQwDQYJKoZIhvcNAQEL
    BQAwPTE7MDkGA1UEAxMyVmF1bHQgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkg
    KGNoYXJtLXBraS1sb2NhbCkwHhcNMjUxMDE1MTY1MTIyWhcNMzUxMDEzMTU1MTUy
    WjA9MTswOQYDVQQDEzJWYXVsdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAo
    Y2hhcm0tcGtpLWxvY2FsKTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
    AMsMIH+m1DXDJBuMkJ3tXYUFgS4chEm2P4mdzNrCP5EImDb4r6SVTsCFQbDxdEl/
    dNWxKpq/3CA8CTm/wEhkMfkl6f3QGicqy8bHrm0MWEB5VC/GjRgh2TBaLES7W4gQ
    AP6YAqw3c37rn5iRaB996qMZlGVMH/b0mDK9hvJrGnRQo3tcgbUvmoejJ2s8Cvzv
    TIDeLZ5CV2N4xguSBumnE9kTUKv0tRnkRL+juWloktFQhSq43OAmSoTOp8wQk1g/
    gclSpevx//BeqdUGx+2L62du7RO0qhN2JVIAszVF3gujxkoABExyXgyeR+avsGm4
    +DJQf/PBtaFyIyX5ReKS85ECAwEAAaNjMGEwDgYDVR0PAQH/BAQDAgEGMA8GA1Ud
    EwEB/wQFMAMBAf8wHQYDVR0OBBYEFACGaexQ74UKxoWpJ41Cx2Qe7Vv5MB8GA1Ud
    IwQYMBaAFACGaexQ74UKxoWpJ41Cx2Qe7Vv5MA0GCSqGSIb3DQEBCwUAA4IBAQBI
    Q1W/8L9QBnwK+/pa0TbySMuzXbTuwVlWmYzviL+XWbMUFkgmwHwDJyc047FcvkqQ
    +cPszlugIZ+52qkboPOdjE51vHSfu+nqUppW/8EIdAqQrJLHBq0wTI/0AaeoAfVr
    svnQtYZ1AF6IXXRDnNz1wLiuGQsFVSQFwLTjdwMMLe0kLK7sKIbW307bmQWUXNx7
    Xf6z37iJbdRXfwq0MgYbtaBKOdd4r9YSSmdMl05t9KUq2zBqGW0izkjZ4tLI9Ciz
    a/WEbQ/9qOjvB2+/Pdf4aFDt2Jv6wizrsvPUwaJCS5kqy6FcG1OzHhzRdokOSd6O
    XJVxd2k3fsZKfNWIYsis
    -----END CERTIFICATE-----
