kind: HelmRepository
apiVersion: source.toolkit.fluxcd.io/v1
metadata:
  name: cern
spec:
  interval: 1h
  url: https://kubernetes.github.io/cloud-provider-openstack/
---
kind: HelmChart
apiVersion: source.toolkit.fluxcd.io/v1
metadata:
  name: openstack-cloud-controller-manager
spec:
  chart: openstack-cloud-controller-manager
  interval: 1h
  version: "2.x"
  sourceRef:
    kind: HelmRepository
    name: cern
---
kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2
metadata:
  name: openstack-cloud-controller-manager
spec:
  interval: 1h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chartRef:
    kind: HelmChart
    name: openstack-cloud-controller-manager
  values:
    # secret is created in /secrets/osccm.yaml
    secret:
      enabled: true
      name: cloud-config
      create: false
