apiVersion: v1
kind: Namespace
metadata:
  name: dragonfly
  labels:
    name: dragonfly
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dragonfly
  namespace: dragonfly
spec:
  interval: 24h
  url: oci://ghcr.io/dragonflydb/dragonfly-operator/helm/dragonfly-operator
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: "1.x"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: dragonfly
spec:
  interval: 12h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chartRef:
    kind: OCIRepository
    name: dragonfly
