apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq-system
---
kind: GitRepository
apiVersion: source.toolkit.fluxcd.io/v1
metadata:
  name: rabbitmq-operator
  namespace: rabbitmq-system
spec:
  interval: 24h
  url: https://github.com/rabbitmq/cluster-operator.git
  ref:
    semver: "v2.x"
---
kind: Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
metadata:
  name: rabbitmq-operator
  namespace: rabbitmq-system
spec:
  interval: 10m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: rabbitmq-operator
  path: config/installation
