apiVersion: v1
kind: Namespace
metadata:
  name: victoriametrics
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoriametrics
  namespace: victoriametrics
spec:
  interval: 24h
  url: https://victoriametrics.github.io/helm-charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: victoria-metrics-operator
  namespace: victoriametrics
spec:
  interval: 24h
  chart: victoria-metrics-operator
  sourceRef:
    kind: HelmRepository
    name: victoriametrics
  version: "0.41.x"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-operator
  namespace: victoriametrics
spec:
  interval: 12h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chartRef:
    kind: HelmChart
    name: victoria-metrics-operator
