apiVersion: ENC[AES256_GCM,data:+n4=,iv:JvlrYuRGO4i3SwdUpK/6Qe1l1kEAnPNcZzBOpmguRPU=,tag:7AHMshinl+MaTEk/IVWYkA==,type:str]
kind: ENC[AES256_GCM,data:Y3lG57ho,iv:3LYtEq8r4kcRPGNAlwP2DWMVg9p1oNDae3o5/3QGF/g=,tag:pLquKyPrOZayLCJVLB/D+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7siDx3o4,iv:GJinzu2BAjuAk8v1ocgN0ZT/ZVlmuuZsvDNctw8aZmc=,tag:pr52XcSHgnvedWOCxj0AUw==,type:str]
    namespace: ENC[AES256_GCM,data:MAep0w6STA==,iv:tc75fAfdF++V9Z3mgZH1FqJoLNnh11znRz+ZQzw7K14=,tag:RFd5Pchsc6kwQzfB5sotqw==,type:str]
    annotations:
        replicator.v1.mittwald.de/replicate-to: ENC[AES256_GCM,data:3W+qvEG7S5fmlteufSeK2151MlBeSg==,iv:Rws/oUJNwH8A+DDfjONYgl07DjdoaH2KMo2GcY1iSbU=,tag:TO2M1xfFeF2b4z3vz60UPw==,type:str]
type: ENC[AES256_GCM,data:62ftvh6/kwNezOw1F/5A8lU9zieyPx1rTs2/xUTb,iv:XysNPZGoQkxl+/NDgBV72C1c122pKC/uYPZNmmpJ6So=,tag:tLQlRmxumTx56Pw+LFuPNw==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/kbs610/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-02-06T20:34:46Z"
          enc: CiQAEE9xLnz/qxSew36KWCIbxXv42DOYvBwwTkDJSDJx+n0giaUSSQAyihV3l0cXA+9IaxehFz6yQJLImvg/+UFCqB3x1b+E/VopACxQsvQzRl86lvuOXHWnZydPhATy5vnHCVHArz9iHsGw8oP7HB0=
    lastmodified: "2026-02-06T20:34:46Z"
    mac: ENC[AES256_GCM,data:i2NT8g3sak167j40ZK+kekh8ON6inj3nXaKAAtUZxvbIo2Ok1TKkCWQ+B5I7yvkImLaRGkW2BHY21w48IzZbsygaJXni4xrM8mEGcPuAWrqU95qKDnFE1nBGtWF3YN2jC+YpXkeyxDTNaptS7c2LIFbs5OMjFrZ0wX3Mqop2VHo=,iv:UwBnXUqtHrjkyBq0zcKKBmBE1hJzSlF0z/OsWHccBec=,tag:KyZ9h4+dsEu840bDykUORA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
