apiVersion: ENC[AES256_GCM,data:ZKs=,iv:vxHLBbfTKJc/UNkgDJGN3dBr/H1k8aeLKEMpUgQQl+k=,tag:imkoQ+29sy+fbJE5VpkvXw==,type:str]
kind: ENC[AES256_GCM,data:/SQ1yz3I,iv:khwBZt6k+2l579aCaUsOPmweDlqRS2JllV9xsRvvumU=,tag:ppQymNGq6pJ2SAhuVwfm9w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DAOI39zk,iv:IWbeEsl+vp9UcL5SjyWrmfJb2JiyescKH9q5U5mhZig=,tag:DqokLvj+7ZJQ79Xqsf5VUA==,type:str]
    namespace: ENC[AES256_GCM,data:qnO/JG2i5w==,iv:ALM5IJbkK95tpg140aD0JNgXycbCZwCC0QYgM4B9mQk=,tag:Eb+EEkVO5/bx+aPVJJ/zXw==,type:str]
    annotations:
        replicator.v1.mittwald.de/replicate-to: ENC[AES256_GCM,data:6qXs5V14eeEsMPcj7wT7wxh92cBhyw==,iv:0kv53NSQrZ/H2y9zbGXujrDtpdyPVlGJzjijkLGJkCU=,tag:hou03HF2RCYsRsG9nvPh6w==,type:str]
type: ENC[AES256_GCM,data:/vWhbX7i,iv:NcLGPzfVRn1nPAXj1afoc3m7ONnAM63w6pG/qBXOBIE=,tag:FfZ2Y5ESQfafJ0zWyNwLSA==,type:str]
stringData:
    geopsKey: ENC[AES256_GCM,data:VjiHua7HpYMiybhWLyh9DZB95/Oi3NHU4d2zGkkwqaGfQ2HWYH9qqHe9v0GgrR8DPyUnMXG1FUQ=,iv:coRsEW5NyHesdQMyteET0qIip7ZRxVXDuuGo3JhfIBw=,tag:66h9T/DsrVBrz0XCuUoeDA==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/kbs610/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-02-06T23:29:14Z"
          enc: CiQAEE9xLq5qSAp2soV6hCGWOm0q2CcqgKZe/9hpcdtjpK126RYSSQAyihV3Rg+ngCLDI57oJI3SGJilD7IA+Q5jh7TphwHl5b2oLH03DqOlIMF3oF8pMU7dPQYKl0s+Ex3gKiB7cri1FFC4m4PodGU=
    lastmodified: "2026-02-06T23:29:14Z"
    mac: ENC[AES256_GCM,data:Y2svWjsZBaePYGoftd61KjueGkcuWyOTqAUqV7QLJrCY+buG3Ihm6XAUgZDNqeQ2Gzi/qct2KySfLeh0Xy2id38yl7/+XIovp8X9VIIgFHyCkLPyK/xzYdnAofa1tteg4Xvww8gcdE54LqWr2JUGV/e4jKdrOlWabPpf4AQUHPU=,iv:6+3YJi9rwNbg6d7xjelnz48rqZkJaB4rodcLvLsf3Ug=,tag:eaKuWoq3AypK63gxzHaV1A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
